
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label idxLabel;

	private global::Gtk.Entry idxTextbox;

	private global::Gtk.Button chooseIdxPathBtn;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Entry searchTextbox;

	private global::Gtk.Button searchBtn;

	private global::Gtk.ScrolledWindow scrolledWindow;

	private global::Gtk.VBox resultVBox;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("CodeSearcher GTK# Client");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-find", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.idxLabel = new global::Gtk.Label();
		this.idxLabel.Name = "idxLabel";
		this.idxLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Index path");
		this.hbox1.Add(this.idxLabel);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.idxLabel]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.idxTextbox = new global::Gtk.Entry();
		this.idxTextbox.CanFocus = true;
		this.idxTextbox.Name = "idxTextbox";
		this.idxTextbox.IsEditable = true;
		this.idxTextbox.MaxLength = 255;
		this.idxTextbox.InvisibleChar = '●';
		this.idxTextbox.Xalign = 1F;
		this.hbox1.Add(this.idxTextbox);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.idxTextbox]));
		w2.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.chooseIdxPathBtn = new global::Gtk.Button();
		this.chooseIdxPathBtn.CanFocus = true;
		this.chooseIdxPathBtn.Name = "chooseIdxPathBtn";
		this.chooseIdxPathBtn.UseUnderline = true;
		this.chooseIdxPathBtn.Label = global::Mono.Unix.Catalog.GetString("...");
		this.hbox1.Add(this.chooseIdxPathBtn);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.chooseIdxPathBtn]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.fixed1.Add(this.hbox1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hbox1]));
		w4.X = 26;
		w4.Y = 17;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.searchTextbox = new global::Gtk.Entry();
		this.searchTextbox.CanFocus = true;
		this.searchTextbox.Name = "searchTextbox";
		this.searchTextbox.IsEditable = true;
		this.searchTextbox.InvisibleChar = '●';
		this.hbox2.Add(this.searchTextbox);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.searchTextbox]));
		w5.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.searchBtn = new global::Gtk.Button();
		this.searchBtn.CanFocus = true;
		this.searchBtn.Name = "searchBtn";
		this.searchBtn.UseUnderline = true;
		this.searchBtn.Label = global::Mono.Unix.Catalog.GetString("Search");
		this.hbox2.Add(this.searchBtn);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.searchBtn]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.fixed1.Add(this.hbox2);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hbox2]));
		w7.X = 29;
		w7.Y = 60;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.scrolledWindow = new global::Gtk.ScrolledWindow();
		this.scrolledWindow.CanFocus = true;
		this.scrolledWindow.Name = "scrolledWindow";
		this.scrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w8 = new global::Gtk.Viewport();
		w8.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.resultVBox = new global::Gtk.VBox();
		this.resultVBox.Name = "resultVBox";
		this.resultVBox.Spacing = 6;
		w8.Add(this.resultVBox);
		this.scrolledWindow.Add(w8);
		this.fixed1.Add(this.scrolledWindow);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.scrolledWindow]));
		w11.X = 29;
		w11.Y = 103;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 706;
		this.DefaultHeight = 504;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
